# Generated by Django 2.1.1 on 2018-10-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(choices=[(0, 'TODO'), (1, 'IN PROGRESS'), (2, 'IN REPOSITORY'), (3, 'TEST'), (4, 'DONE')], default=0),
        ),
    ]
