# Generated by Django 2.1.1 on 2018-10-29 21:44

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181020_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproject',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
