# Generated by Django 2.1.1 on 2018-10-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notifications_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='is_active',
        ),
        migrations.AddField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
